title: igvReader variant classifier
description: Classify SNVs as positive or negative using deep learning 
about:
  This is a bear Images Classifier using Deep Learning built on top of Pytorch.

  The project referenced this project [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.

  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    
  - [Web app](https://food-img-classifier.herokuapp.com)
  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)

  To try out this mobile app
    - [Expo](https://expo.io/@npatta01/food-app)
    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)
    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)

code: https://github.com/stuartzong/beardetector

sampleImages:
  - name: real positive1
    url: https://igvreader.herokuapp.com/static/images/chr15_43,075,667_43,075,967.png
  - name: real positive2
    url: https://igvreader.herokuapp.com/static/images/chr7_32,912,815_32,913,115.png
  - name: false postive1
    url: https://igvreader.herokuapp.com/static/images/chr1_7,196,997_7,197,297.png
  - name: false postive2
    url: https://igvreader.herokuapp.com/static/images/chr3_195,509,519_195,509,819.png

