title: bear classifier
description: Classify grizzly, black, and teddy bears using deep learning
about:


  This is a Food Images Classifier using Deep Learning built on top of Pytorch.


  The project was build by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    

  - [Web app](https://food-img-classifier.herokuapp.com)

  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


  To try out this mobile app

    - [Expo](https://expo.io/@npatta01/food-app)

    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)

    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)



code: https://github.com/stuartzong/beardetector

sampleImages:
  - name: grizzly bear
    url: https://www.mtpr.org/sites/kufm/files/styles/x_large/public/201809/grizzly-bear-02_Istock.jpg
  - name: teddy bear
    url: https://www.ikea.com/PIAimages/0531366_PE647283_S5.JPG?f=s
  - name: black bear
    url: https://www.google.com/search?q=black+bear&safe=active&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi3y96x_eXlAhXQl54KHfw0Cc8Q_AUIEigB&biw=596&bih=588
