title: igvReader variant classifier
description: Classify SNVs as positive or negative using deep learning 
about:
  This is a bear Images Classifier using Deep Learning built on top of Pytorch.

  The project referenced this project [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.

  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    
  - [Web app](https://food-img-classifier.herokuapp.com)
  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)

  To try out this mobile app
    - [Expo](https://expo.io/@npatta01/food-app)
    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)
    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)

code: https://github.com/stuartzong/beardetector

sampleImages:
  - name: real positive
    url: https://lh3.googleusercontent.com/hKC4OdcVlnu9zd3JwSdzO5a1Vd8398esmnkez99ihh7Bwf5cnJ4aX8BL7fsAv5Tpf67UM7Sc0KquoKh7U8ZS47ajNIH4dHcOT29mt9E-6XJt3TgvcBHy8aQEmq-KreKQ6Bi6ZTHgsveYGoTW35JYFo-Axobne3KmnZPwnwn6OthNK7Q1ROs9c1FbPpL7RUHJTrKsdHc5Zctm_6jOGE0pXHKWfmIm1CYsTn9AnKXS6CshTmMZ2W5DFALxatzSj8iN66FGOLaT8R1-aT_3h5-5nCDrbRYBqZhPpvmE88IAa6mV3jXokAfoKCAlZllAlhOyIpuyJr3Ev9Fu1-4eOF5gNwx9LyONJUqDbzSk7xki6J2SFw6AlMRyPxH_JkVbVIWz821iKP7Rwj8UkH-8h3vCHv_1ceenlkhFBPVQzSj4pSGApgC6gfnMF9HxnUgi2WjpPMMDBwsB321j5yBDzb6tSVwZwB8CY_VzldVzJftg36vuSLY1FEik0rHyOjzmayAGZVzCvQTDuxaUP3oNTTSte5sX_nc5JzP_o4PpK1T8UWgE8_FLb1-OTOLNFyRBtZEd7bS284UmIhiZkgvrQOxMEWXtWfth7lu_YqthvQZEOiUqSXFIli_HOx1hLNvYpMJlxu6Dnn0b6Lp_KqUfBRwpy0Ii8w_EoQU26NPFxIpad2pVwoBJTKMs5nA=w800-h200-no
  - name: false postive
    url: https://lh3.googleusercontent.com/jEqEpp7IYXiuGXjx7xKJURjyTpdXG9P0JS6OR2cRH8RaucupUfrDvmojldqzR1kadzte7b1_T6DWWf-bnIvqFntsCBVUyDrfbSaL-5Ynt3D98xYkN8XutJcTIBPqeX6zHqdqZrABGmluiX1n6vzxdACP_asQnk6M-D9fUTPoJAsTyA-ieq1gRPlpJt_PPQfByZmT8YA8f8Qfm-y20IubEh-3YHKz4sSi_b3innl37pEVXq1DzrgWno9rmBpzhIRFI29DMH4GkRjhfOO45DtFDOm4tL2eACJt6358ooYpMj4LCR0vmdAjywpVNnhh9XO8JT9DxahLgIFoN8aHVd2XLh7iMenMQgz1iTHEAHwV8Wjx5IpS_JsG0zTzlEmkwmG4gWzJyAKa8gEAxqJC_zHBnVOJ1WaJjsBBdnPTFju9G188QAkFGIxirVecmPAPjYrMb7pQH6jefBFxBNl6XeYYaxNNfxmHLziDAegnF9STZCOwvASDLk3GFaSGDSfzlq68W5LmtNB-mgMyUf8-F6BACxGxY1UWoGwRruW2VAMxn9uSqE3vgRUTWU4mAHI7OGQiLo3LJAMwVzFMdI1Vcwq0RpJaDPLdH3nYhGvT-YnH9gJ9ZvQAsVxupAE00GcN0J2Lmf4rPx4Car6JGW4G_P9P2WZy4XYjd30aiDMfJW-rN8ffMfkYZuJkjRg=w800-h200-no
